version: "3.7"
services:
  app:
    build:
      context: .
    image: gradle:jdk11

    volumes:
      - .:/app
    working_dir: /app
    entrypoint: bash #gradle build # && gradle shadowJar && java -jar /app/build/libs/orderapp-all.jar /app/src/main/resources/orders.csv /app/src/main/resources/orders.xml